# Generated by Django 5.2.1 on 2026-01-22 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brend nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Model nomi')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ishlab chiqarilgan yil')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kunlik narx ($)')),
                ('mileage', models.IntegerField(default=0, verbose_name='Yurgan masofa (km)')),
                ('fuel_type', models.CharField(choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektro', 'Elektro'), ('gibrid', 'Gibrid')], default='benzin', max_length=20, verbose_name="Yoqilg'i turi")),
                ('transmission', models.CharField(choices=[('avtomat', 'Avtomat'), ('mexanik', 'Mexanik'), ('robot', 'Robot')], default='avtomat', max_length=20, verbose_name='Uzatmalar qutisi')),
                ('seats', models.IntegerField(default=5, verbose_name="O'rindiqlar soni")),
                ('color', models.CharField(max_length=50, verbose_name='Rang')),
                ('image', models.ImageField(default='cars/default.jpg', upload_to='cars/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('mavjud', 'Mavjud'), ('ijarada', 'Ijarada'), ("ta'mirlanmoqda", "Ta'mirlanmoqda")], default='mavjud', max_length=20, verbose_name='Holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etiladi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='apps.brand', verbose_name='Brend')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('total_days', models.IntegerField(default=1, verbose_name='Kunlar soni')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami narx ($)')),
                ('message', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha xabar")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('completed', 'Yakunlandi')], default='pending', max_length=20, verbose_name='Holat')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin eslatmalari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='apps.car', verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': 'Ijara arizasi',
                'verbose_name_plural': 'Ijara arizalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
